const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'/Volumes/external/projects/homeservices/node_modules/@playwright/test');
const fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict'),{pathToFileURL}=require('node:url');
const builder=path.resolve(__dirname,'..'),root=path.dirname(builder);
(async()=>{
 const plans=JSON.parse(await fs.readFile(path.join(builder,'reports/build-manifest.json'))),browser=await chromium.launch({headless:true}),results=[];let next=0;
 const markdown='# Recommendation\n\nUse **reviewed facts** to prepare the next step.\n\n## Action plan\n1. Check the inputs.\n2. Review the result.\n\n| Item | Action |\n| --- | --- |\n| Evidence | Verify source |\n\n[Source](https://example.com)\n\n<script>window.aiUnsafe=true</script>\n\n[unsafe](javascript:alert(1))\n\n```text\nExample only\n```';
 async function worker(){while(next<plans.length){const plan=plans[next++],dir=path.join(root,plan.id);if(process.env.PLATFORMS&&!process.env.PLATFORMS.split(',').includes(plan.id))continue;let server,context,temp;
 try{
  const load=rel=>import(pathToFileURL(path.join(dir,'dist',rel))),{createHub}=await load('hub/server.mjs'),{openStore}=await load('hub/runtime/store.mjs'),{seedWorkspace}=await load('scripts/seed.mjs'),{features,assistants}=await load('scripts/workspace.mjs');
  const aiFeatures=features.filter(f=>f.ai),f=aiFeatures.find(f=>f.id===assistants[0].representativeId);assert.ok(f);
  temp=await fs.mkdtemp(path.join(os.tmpdir(),'platform-assistant-'));const databasePath=path.join(temp,'test.sqlite'),store=openStore(databasePath,features);seedWorkspace(store);store.close();let calls=[];
  server=createHub({databasePath,complete:async payload=>{calls.push(payload);await new Promise(r=>setTimeout(r,120));if(payload.messages.at(-1).content.includes('FAIL_TEST'))throw new Error('Hidden provider response');return {model:'browser-test-provider',choices:[{message:{content:markdown}}]};}});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const base=`http://127.0.0.1:${server.address().port}`;
  context=await browser.newContext({viewport:{width:1440,height:1000}});const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto(base+f.path);await page.locator('.question-input').waitFor();assert.equal(await page.locator('tbody tr').count(),0,'AI page must replace record table');
  const q=page.locator('[name="question"]'),ask=page.getByRole('button',{name:'Ask AI',exact:true}),history=page.getByRole('combobox',{name:'Saved AI answers'});
  await q.fill('How should I review these facts?');await page.locator('.assistant-context summary').click();await page.locator('[name="context"]').fill('The deadline is next week.');await page.locator('[name="recordId"]').selectOption({index:1});await ask.click();await page.locator('.answer-markdown').waitFor();assert.equal(calls.length,1);assert.match(calls[0].messages.at(-1).content,/deadline is next week/);assert.ok(JSON.parse(calls[0].messages.at(-1).content).selectedRecord.id);
  assert.equal(await page.locator('.answer-markdown h2').first().textContent(),'Recommendation');assert.equal(await page.locator('.answer-markdown strong').textContent(),'reviewed facts');assert.equal(await page.locator('.answer-markdown ol li').count(),2);assert.equal(await page.locator('.answer-markdown table tbody tr').count(),1);assert.equal(await page.locator('.answer-markdown script').count(),0);assert.equal(await page.locator('.answer-markdown a[href^="javascript:"]').count(),0);assert.equal(await page.evaluate(()=>Boolean(window.aiUnsafe)),false);
  await page.waitForFunction(()=>document.querySelector('.assistant-status').textContent.includes('Answer saved'));await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:path.join(dir,'reports/ai-answer-desktop.png')});
  const first=(await (await context.request.get(base+`/api/workspace/features/${f.id}/answers`)).json())[0];assert.ok(first.id);await q.fill('Give me a shorter follow-up.');await ask.click();await page.waitForFunction(()=>document.querySelector('.answer-heading h2')?.textContent==='Give me a shorter follow-up.');assert.equal(calls.length,2);assert.equal(calls[1].messages.length,4);
  await page.reload();await history.waitFor();await page.waitForFunction(()=>document.querySelector('.answer-history select').options.length===3);await history.selectOption(first.id);await page.waitForFunction(()=>document.querySelector('.answer-heading h2')?.textContent==='How should I review these facts?');assert.equal(await page.locator('[name="context"]').inputValue(),'The deadline is next week.');
  const downloadEvent=page.waitForEvent('download');await page.getByRole('button',{name:'Download',exact:true}).click();const download=await downloadEvent;assert.ok(download.suggestedFilename().endsWith('-answer.md'));
  await page.getByRole('button',{name:'New question',exact:true}).click();await q.fill('FAIL_TEST');await ask.click();await page.locator('.assistant-error').waitFor({state:'visible'});assert.equal(await q.inputValue(),'FAIL_TEST');assert.doesNotMatch(await page.locator('.assistant-error').textContent(),/Hidden provider response/);assert.equal((await (await context.request.get(base+`/api/workspace/features/${f.id}/answers`)).json()).length,2);
  await q.fill('Try a fresh answer.');await ask.click();await page.locator('.answer-markdown').waitFor();assert.equal(calls.length,4);assert.equal(calls[3].messages.length,2);await page.waitForFunction(()=>document.querySelector('.assistant-status').textContent.includes('Answer saved'));
  const before=calls.length;let response=await context.request.post(base+`/api/workspace/features/${f.id}/ask`,{headers:{'X-Legal-Workspace':'1',Origin:'https://example.com'},data:{question:'Forbidden'}});assert.equal(response.status(),403);assert.equal(calls.length,before);
  const other=aiFeatures.find(x=>x.id!==f.id);if(other){response=await context.request.get(base+`/api/workspace/features/${other.id}/answers/${first.id}`);assert.equal(response.status(),404);}
  await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'No mobile overflow');await page.screenshot({path:path.join(dir,'reports/ai-answer-mobile.png'),fullPage:true});
  // Check every AI feature route: the primary experience must be a question form, never a record table.
  await page.setViewportSize({width:1440,height:1000});for(const candidate of aiFeatures){await page.evaluate(url=>{history.pushState({},'',url);dispatchEvent(new PopStateEvent('popstate'));},candidate.path);await page.getByRole('heading',{name:assistants.find(a=>a.featureIds.includes(candidate.id)).title,exact:true}).waitFor();await page.locator('.question-input').waitFor();assert.equal(await page.locator('#content .record-row').count(),0,candidate.id);assert.equal(await page.locator('#error').isVisible(),false,candidate.id);}
  // Existing non-AI CRUD and row popup remain available.
  await page.goto(base+'/features/clients');await page.locator('.record-row').first().click();await page.locator('#row-dialog[open]').waitFor();await page.locator('#row-dialog').getByRole('button',{name:'Edit',exact:true}).waitFor();assert.deepEqual(errors,[]);
  await context.close();context=null;await new Promise(resolve=>server.close(resolve));server=null;
  server=createHub({databasePath,complete:async()=>{throw new Error('No new AI request expected');}});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const reopened=await fetch(`http://127.0.0.1:${server.address().port}/api/workspace/features/${f.id}/answers/${first.id}`);assert.equal(reopened.status,200);assert.equal((await reopened.json()).answer,markdown);
  const report={id:plan.id,status:'passed',aiPagesVisited:aiFeatures.length,replacedTables:true,questionAnswer:true,selectedContext:true,followups:true,persistedHistory:true,persistenceAcrossRestart:true,markdownAndTables:true,safeRendering:true,download:true,providerFailureRecovery:true,originProtection:true,featureIsolation:true,mobile:true,nonAIRecordPopup:true,provider:'mocked; no live provider call',verifiedAt:new Date().toISOString()};results.push(report);await fs.writeFile(path.join(dir,'reports/ai-workspace-verification.json'),JSON.stringify(report,null,2));console.log(`${results.length}/64 AI workspace passed: ${plan.id} (${aiFeatures.length} AI pages)`);
 }catch(e){results.push({id:plan.id,status:'failed',error:e.stack});console.log(`FAILED ${plan.id}: ${e.stack}`);}
 finally{if(context)await context.close();if(server)await new Promise(resolve=>server.close(resolve));if(temp)await fs.rm(temp,{recursive:true,force:true});await fs.writeFile(path.join(builder,'reports/ai-workspace-results.json'),JSON.stringify(results,null,2));}
 }}
 try{await Promise.all(Array.from({length:4},worker));}finally{await browser.close();}if(results.some(r=>r.status==='failed'))process.exitCode=1;
})().catch(e=>{console.error(e);process.exitCode=1});
